name: Release

on:
  push:
    branches: [ master ]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
      - name: Install
        run: npm install
      - name: Test
        run: npm run test
      - name: Build
        run: npm run build
      - name: Publish to npm
        id: publish
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_TOKEN }}
          package: ./dist/efaps/pos-library/package.json
      - name: Create Release
        if: steps.publish.outputs.type != 'none'
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.publish.outputs.version }}
          release_name: Release ${{ steps.publish.outputs.version }}
          draft: false
          prerelease: false
